inputs:
  test_name:
    required: true
    description: "Test name"
  commands:
    required: true
    description: "Shell commands to run the test"
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - run: |
        set -x
        export MAGIC_ENV=wormhole_b0_80_arch_eth_dispatch.yaml

        ${{ inputs.commands }}

        export DEVICE_PERF_REPORT_FILENAME=Models_Device_Perf_${{ inputs.test_name }}_$(date +%Y_%m_%d).csv
        python3 models/perf/merge_device_perf_results.py $DEVICE_PERF_REPORT_FILENAME ${{ inputs.test_name }}
        echo "device_perf_report_filename=$DEVICE_PERF_REPORT_FILENAME" >> "$GITHUB_OUTPUT"
      shell: bash
      env:
        TRACY_NO_INVARIANT_CHECK: 1
      volumes:
        - ${{ github.workspace }}/docker-job:/work # Subdir to workaround https://github.com/actions/runner/issues/691
        - /dev/hugepages-1G:/dev/hugepages-1G
        - /mnt/MLPerf:/mnt/MLPerf:ro