inputs:
  test_name:
    required: true
    description: "Test name"
  commands:
    required: true
    description: "Shell commands to run the test"
runs:
  using: "composite"
  steps:
    - run: |
        ls /opt/runner/_work/tt-metal/tt-metal/tests/scripts
        ls ${{ github.workspace }}/tests/scripts/common.py
        cd ${{ github.workspace }}
        set -x
        export MAGIC_ENV=wormhole_b0_80_arch_eth_dispatch.yaml

        export PYTHONPATH=${{ github.workspace }}

        ${{ inputs.commands }}

        export DEVICE_PERF_REPORT_FILENAME=Models_Device_Perf_${{ inputs.test_name }}_$(date +%Y_%m_%d).csv
        python3 models/perf/merge_device_perf_results.py $DEVICE_PERF_REPORT_FILENAME ${{ inputs.test_name }}
        echo "device_perf_report_filename=$DEVICE_PERF_REPORT_FILENAME" >> "$GITHUB_OUTPUT"
      shell: bash
      env:
        TRACY_NO_INVARIANT_CHECK: 1
