name: "[impl] C++ unit tests"

on:
  workflow_call:
    inputs:
      docker-image:
        required: true
        type: string
      package-artifact-name:
        required: true
        type: string
      runner:
        required: true
        type: string
      per-test-timeout:
        required: false
        type: string
        default: 5.0
      product:
        required: true
        type: string

jobs:
  cpp-unit-tests:
    runs-on: ${{ format('tt-beta-ubuntu-2204-{0}-large-stable', inputs.runner) }}
    container:
      image: harbor.ci.tenstorrent.net/${{ inputs.docker-image || 'docker-image-unresolved!'}}
      volumes:
        - /work
        - /dev/hugepages-1G:/dev/hugepages-1G
      options: --device /dev/tenstorrent
    defaults:
      run:
        shell: bash
        working-directory: /work
    steps:
      - name: Download package artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.package-artifact-name || 'packages artifact unresolved!' }}
          path: /work/pkgs/
      - name: Install packages
        run: |
          set -euo pipefail
          apt update
          apt install -y ./pkgs/tt-metalium_*.deb ./pkgs/tt-metalium-jit_*.deb ./pkgs/tt-metalium-validation_*.deb
      - name: Run tests
        run: |
          set -euo pipefail
