name: Merge Gate
# This pipeline is the minimum bar a PR must pass before it can pass the merge queue.
# It is intended to be relatively fast and lightweight that the delay between completing
# a PR and having the changes available on main is not onerous.

# Requirements for all jobs in this workflow:
# - End-to-end (excluding wait times for runners) must be less than 15mins.
#   This includes the cost of checking out the code, preparing a runner, etc.
# - Individual test cases must be less than 5s.

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  merge_group:
  push:
    branches:
      - main # Builds on main will populate the shared ccache to speed up builds on branches

permissions:
  contents: write
  pull-requests: write
  checks: write
  packages: write

jobs:

  find-changes:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    outputs:
      any-code-changed: ${{ steps.find-changes.outputs.any-code-changed }}
      docs-changed: ${{ steps.find-changes.outputs.docs-changed }}
      cmake-changed: ${{ steps.find-changes.outputs.cmake-changed }}
      tt-metalium-changed: ${{ steps.find-changes.outputs.tt-metalium-changed }}
      tt-nn-changed: ${{ steps.find-changes.outputs.tt-nn-changed }}
      tt-metalium-or-tt-nn-tests-changed: ${{ steps.find-changes.outputs.tt-metalium-or-tt-nn-tests-changed }}
    steps:
      - id: find-changes
        uses: tenstorrent/tt-metal/.github/actions/find-changed-files@main

  build-asan:
    if: ${{ github.ref_name == 'main' ||
            needs.find-changes.outputs.cmake-changed == 'true' ||
            needs.find-changes.outputs.any-code-changed == 'true'
        }}
    needs: find-changes
    uses: ./.github/workflows/build-artifact.yaml
    permissions:
      packages: write
    secrets: inherit
    with:
      build-type: ASan
      version: 22.04
      skip-tt-train: false
      publish-artifact: false

  metalium-basic-tests:
    if: ${{
        github.ref_name == 'main' ||
        needs.find-changes.outputs.cmake-changed == 'true' ||
        needs.find-changes.outputs.tt-metalium-changed == 'true' ||
        needs.find-changes.outputs.tt-metalium-or-tt-nn-tests-changed == 'true'
      }}
    needs: [ build-asan, find-changes ]
    strategy:
      fail-fast: false
      matrix:
        platform: [
          "N150",
          "P150b-viommu",
          "P150b-viommu",
          "P150b-viommu",
        ]
    uses: ./.github/workflows/basic.yaml
    with:
      docker-image: ${{ needs.build-asan.outputs.dev-docker-image }}
      package-artifact-name: ${{ needs.build-asan.outputs.packages-artifact-name }}
      per-test-timeout: 11
      runner: ${{ matrix.platform }}
      product: tt-metalium

  ttnn-basic-tests:
    needs: [build-asan, find-changes]
    if: ${{ github.ref_name == 'main' ||
            needs.find-changes.outputs.cmake-changed == 'true' ||
            needs.find-changes.outputs.tt-nn-changed == 'true' ||
            needs.find-changes.outputs.tt-metalium-or-tt-nn-tests-changed == 'true'
        }}
    strategy:
      fail-fast: false
      matrix:
        platform: [
          "N150",
          "P150b-viommu",
          "P150b-viommu",
          "P150b-viommu",
        ]
    uses: ./.github/workflows/basic.yaml
    with:
      docker-image: ${{ needs.build-asan.outputs.dev-docker-image }}
      package-artifact-name: ${{ needs.build-asan.outputs.packages-artifact-name }}
      per-test-timeout: 11
      runner: ${{ matrix.platform }}
      product: tt-nn

  # GitHub has so many design limitations it's not even funny.
  # This job is purely so we can capture the essence of the workflow as a whole in our status checks.
