name: "(Single-card) Device perf regressions"

on:
  workflow_dispatch:
    inputs:
      run_cnn_models:
        description: 'CNNs'
        required: false
        default: true
        type: boolean
      run_other_models:
        description: 'Other'
        required: false
        default: true
        type: boolean
  schedule:
    - cron: "0 2,7,10,14,17,20,23 * * *"
  workflow_call:
    inputs:
      run_cnn_models:
        description: 'Run CNN models'
        required: false
        default: true
        type: boolean
      run_other_models:
        description: 'Run other models'
        required: false
        default: true
        type: boolean

jobs:
  build-artifact-profiler:
    uses: ./.github/workflows/build-artifact.yaml
    permissions:
      packages: write
    secrets: inherit
    with:
      tracy: true
      build-wheel: true
      version: 22.04
  device-perf:
    needs: build-artifact-profiler
    secrets: inherit
    uses: ./.github/workflows/perf-device-models-impl.yaml
    with:
      docker-image: ${{ needs.build-artifact-profiler.outputs.dev-docker-image }}
      build-artifact-name: ${{ needs.build-artifact-profiler.outputs.build-artifact-name }}
      wheel-artifact-name: ${{ needs.build-artifact-profiler.outputs.wheel-artifact-name }}
      run_cnn_models: ${{ inputs.run_cnn_models || true }}
      run_other_models: ${{ inputs.run_other_models || true }}
