name: "(Single) Choose your pipeline"

on:
  workflow_dispatch:
    inputs:
      build-type:
        required: false
        type: choice
        options:
          - Release
          - Debug
          - RelWithDebInfo
          - ASan
          - TSan
        default: "Release"
      build-with-tracy:
        required: false
        type: boolean
        default: false
      single-card-demo:
        required: false
        type: boolean
        default: false
      single-card-perf-models:
        required: false
        type: boolean
        default: false
      single-card-perf-device-models:
        description: "perf-device (requires tracy build)"
        required: false
        type: boolean
        default: false
      single-card-nightly:
        required: false
        type: boolean
        default: false
      cpp-unit:
        required: false
        type: boolean
        default: false

run-name: ${{ inputs.description }}
jobs:
  build-artifact:
    uses: ./.github/workflows/build-artifact.yaml
    secrets: inherit
    with:
      build-type: ${{ inputs.build-type }}
      tracy: ${{ inputs.build-with-tracy }}
      build-wheel: true
      version: "22.04"
  single-card-demo-tests:
    needs: build-artifact
    secrets: inherit
    if: ${{ inputs.single-card-demo }}
    uses: ./.github/workflows/single-card-demo-tests-impl.yaml
    with:
      docker-image: ${{ needs.build-artifact.outputs.dev-docker-image }}
      build-artifact-name: ${{ needs.build-artifact.outputs.build-artifact-name }}
      wheel-artifact-name: ${{ needs.build-artifact.outputs.wheel-artifact-name }}
      arch: wormhole_b0
  single-card-perf-models-tests:
    needs: build-artifact
    secrets: inherit
    uses: ./.github/workflows/perf-models-impl.yaml
    with:
      docker-image: ${{ needs.build-artifact.outputs.dev-docker-image }}
      build-artifact-name: ${{ needs.build-artifact.outputs.build-artifact-name }}
      wheel-artifact-name: ${{ needs.build-artifact.outputs.wheel-artifact-name }}
    if: ${{ inputs.single-card-perf-models }}
  single-card-perf-device-models-tests:
    needs: build-artifact
    secrets: inherit
    uses: ./.github/workflows/perf-device-models-impl.yaml
    if: ${{ inputs.single-card-perf-device-models }}
    with:
      docker-image: ${{ needs.build-artifact.outputs.dev-docker-image }}
      build-artifact-name: ${{ needs.build-artifact.outputs.build-artifact-name }}
      wheel-artifact-name: ${{ needs.build-artifact.outputs.wheel-artifact-name }}
  single-card-frequent-models-and-ttnn-tests:
    needs: build-artifact
    secrets: inherit
    uses: ./.github/workflows/fast-dispatch-full-regressions-and-models-impl.yaml
    with:
      docker-image: ${{ needs.build-artifact.outputs.dev-docker-image }}
      build-artifact-name: ${{ needs.build-artifact.outputs.build-artifact-name }}
      wheel-artifact-name: ${{ needs.build-artifact.outputs.wheel-artifact-name }}
    if: ${{ inputs.single-card-nightly }}
  l2-wormhole-tests:
    needs: build-artifact
    strategy:
      fail-fast: false
      matrix:
        test-group:
          - name: ttnn nightly conv tests
            cmd: pytest tests/ttnn/nightly/unit_tests/operations/conv -xv -m "not disable_fast_runtime_mode"
            owner: U052J2QDDKQ # Pavle Josipovic
          - name: ttnn nightly pool tests
            cmd: pytest tests/ttnn/nightly/unit_tests/operations/pool -xv -m "not disable_fast_runtime_mode"
            owner: U052J2QDDKQ # Pavle Josipovic
    container:
      image: ${{ needs.build-artifact.outputs.dev-docker-image }}
      env:
        PYTHONPATH: /work
        LD_LIBRARY_PATH: /work/build/lib
        ARCH_NAME: 'wormhole_b0'
        LOGURU_LEVEL: INFO
      volumes:
        - ${{ github.workspace }}/docker-job:/work # Subdir to workaround https://github.com/actions/runner/issues/691
        - /dev/hugepages-1G:/dev/hugepages-1G
      options: "--device /dev/tenstorrent"
    defaults:
      run:
        shell: bash
        working-directory: /work # https://github.com/actions/runner/issues/878
    name: ${{ matrix.test-group.name }}
    runs-on:
      - ${{ 'N150' }}
      - "in-service"
    steps:
      - name: ⬇️  Setup Job
        uses: tenstorrent/tt-metal/.github/actions/setup-job@main
        timeout-minutes: 10
        with:
          build-artifact-name: ${{ needs.build-artifact.outputs.build-artifact-name }}
          wheel-artifact-name: ${{ needs.build-artifact.outputs.wheel-artifact-name }}
      - name: ${{ matrix.test-group.name }} tests
        timeout-minutes: ${{ (github.event_name == 'schedule' && 120) || fromJSON(inputs.timeout) }}
        run: ${{ matrix.test-group.cmd }}
      - uses: tenstorrent/tt-metal/.github/actions/upload-artifact-with-job-uuid@main
        timeout-minutes: 10
        if: ${{ !cancelled() }}
        with:
          prefix: "test_reports_"
      - uses: tenstorrent/tt-metal/.github/actions/cleanup@main
        if: always()
