name: "(TG) Choose your pipeline"

on:
  workflow_dispatch:
    inputs:
      build-type:
        required: false
        type: choice
        options:
          - Release
          - Debug
          - RelWithDebInfo
          - ASan
          - TSan
        default: "Release"
      topology:
        required: false
        type: choice
        options:
          - config-tg
          - topology-6u
        default: "topology-6u"
      extra-tag:
        required: true
        type: string
        default: "g11glx6u03"
      tg-quick:
        required: false
        type: boolean
        default: true
      tg-stress:
        required: false
        type: boolean
        default: false
run-name: ${{ inputs.description }}
jobs:
  build-artifact:
    uses: ./.github/workflows/build-artifact.yaml
    secrets: inherit
    with:
      build-type: ${{ inputs.build-type }}
      tracy: ${{ inputs.tg-model-perf || inputs.tg-nightly }}
      build-wheel: true
      version: 22.04
  tg-quick:
    if: ${{ inputs.tg-quick }}
    needs: build-artifact
    secrets: inherit
    uses: ./.github/workflows/tg-quick.yaml
    with:
      extra-tag: ${{ inputs.extra-tag }}
      docker-image: ${{ needs.build-artifact.outputs.dev-docker-image }}
      wheel-artifact-name: ${{ needs.build-artifact.outputs.wheel-artifact-name }}
      build-artifact-name: ${{ needs.build-artifact.outputs.build-artifact-name }}
  tg-stress-test:
    needs: build-artifact
    if: ${{ inputs.tg-stress }}
    secrets: inherit
    uses: ./.github/workflows/tg-stress.yaml
    with:
      extra-tag: ${{ inputs.extra-tag }}
      docker-image: ${{ needs.build-artifact.outputs.dev-docker-image }}
      wheel-artifact-name: ${{ needs.build-artifact.outputs.wheel-artifact-name }}
      build-artifact-name: ${{ needs.build-artifact.outputs.build-artifact-name }}
