name: "Custom test dispatch"

on:
  workflow_dispatch:
    inputs:
      arch:
        required: true
        type: choice
        options:
          - wormhole_b0
          - blackhole
      runner-label:
        description: 'Optional: N150, N300, BH, config-t3000, config-tg'
        required: true
        type: string
        default: '["in-service"]'
      build-type:
        required: false
        type: choice
        options:
          - Release
          - Debug
          - RelWithDebInfo
          - ASan
          - TSan
      tracy:
        required: false
        type: boolean
        default: false
        description: "Build with tracy enabled"
      command:
        required: true
        type: string
      description:
        type: string
        default: "Custom test dispatch"
        required: false
      version:
        required: false
        type: choice
        default: "22.04"
        options:
            - "22.04"
            - "24.04"

run-name: ${{ inputs.description }}
jobs:
  # setup:
  #   name: Setup runner labels for deploy
  #   runs-on: ubuntu-latest
  #   outputs:
  #     deployrunner: ${{ steps.step1.outputs.deployrunner }}
  #   steps:
  #     - name: Set runs-on for deploy
  #       id: step1
  #       run: |
  #         # local_var="\'[\"${{ inputs.hw-config }}\", \"${{ inputs.runner-label }}\"]\'"
  #         echo "deployrunner=${{ inputs.runner-label }}" >> $GITHUB_OUTPUT
  test-dispatch:
    timeout-minutes: 1440
    runs-on: ${{ fromJSON(inputs.runner-label) }}
    steps:
      - name: ⬇️ Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Run regression in loop in docker
        run: |
          ${{ inputs.command }}
